import json
import os
import warnings

import numpy as np
import pandas as pd
import pickle
import plotly.graph_objects as go
import plotly.express as px
import streamlit as st

warnings.filterwarnings("ignore")

st.set_page_config(page_title="Favorita Sales Forecasting", layout="wide", page_icon="📈")

# ---------------------------------------------------------
# Paths (relative to repo root — Streamlit Cloud runs from there)
# ---------------------------------------------------------
MODEL_PATH = "models/lgbm_model.pkl"
DATA_PATH = "data/processed/feature_store.csv"
COMPARISON_PATH = "reports/model_comparison_table.csv"
FEATURE_IMPORTANCE_IMG = "reports/lgbm_feature_importance.png"
PROPHET_IMG = "reports/prophet_components_holidays.png"

# Precomputed classical-model artifacts. These are NOT generated by this app —
# they're exported once from the notebook (on the full multi-year national
# series) and committed to the repo. See the "export_artifacts" snippet in the
# notebook / README for how to regenerate them.
ARIMA_SUMMARY_PATH = "reports/arima_summary.txt"
SARIMA_SUMMARY_PATH = "reports/sarima_summary.txt"
PROPHET_SUMMARY_PATH = "reports/prophet_summary.json"
ARIMA_FORECAST_PATH = "reports/arima_forecast.csv"
SARIMA_FORECAST_PATH = "reports/sarima_forecast.csv"
PROPHET_FORECAST_PATH = "reports/prophet_forecast.csv"

# Exact feature order the trained LightGBM Booster expects.
# (Verified directly against the model with model.feature_name() —
# do not reorder or rename these.)
# NOTE: `is_anomaly` sits in this list because that's how the pickled model
# was trained. Worth flagging: if `is_anomaly` is derived from the sales
# value itself, it's a leakage risk for a live forecasting feature — fine for
# this diagnostic dashboard (we already know the label), but don't reuse this
# feature list for a true forward forecast without checking how it's built.
MODEL_FEATURES = [
    "day_of_week", "month", "is_weekend", "is_month_start", "is_month_end",
    "month_sin", "month_cos", "dow_sin", "dow_cos",
    "sales_lag_1", "sales_lag_7", "sales_lag_14", "sales_lag_28",
    "rolling_mean_7", "rolling_mean_28", "rolling_std_7", "rolling_std_28",
    "expanding_mean_sales", "dcoilwtico",
    "promo_lag_1", "promo_lag_7", "promo_rolling_mean_7",
    "is_holiday", "is_national_holiday", "days_to_next_holiday", "is_anomaly",
]

# Plain-English labels used in the SHAP anomaly narrative below.
FEATURE_LABELS = {
    "day_of_week": "day of the week",
    "month": "month of year",
    "is_weekend": "weekend flag",
    "is_month_start": "start-of-month flag",
    "is_month_end": "end-of-month flag",
    "month_sin": "seasonal month position (sin)",
    "month_cos": "seasonal month position (cos)",
    "dow_sin": "seasonal weekday position (sin)",
    "dow_cos": "seasonal weekday position (cos)",
    "sales_lag_1": "sales 1 day earlier",
    "sales_lag_7": "sales 7 days earlier (same weekday)",
    "sales_lag_14": "sales 14 days earlier",
    "sales_lag_28": "sales 28 days earlier",
    "rolling_mean_7": "7-day rolling average sales",
    "rolling_mean_28": "28-day rolling average sales",
    "rolling_std_7": "7-day sales volatility",
    "rolling_std_28": "28-day sales volatility",
    "expanding_mean_sales": "all-time average sales to date",
    "dcoilwtico": "oil price (WTI)",
    "promo_lag_1": "on-promotion flag, 1 day earlier",
    "promo_lag_7": "on-promotion flag, 7 days earlier",
    "promo_rolling_mean_7": "7-day rolling promo intensity",
    "is_holiday": "local/regional holiday flag",
    "is_national_holiday": "national holiday flag",
    "days_to_next_holiday": "days until next holiday",
    "is_anomaly": "flagged-anomaly indicator",
}

FAMILY_NAMES = {
    0: "AUTOMOTIVE", 1: "BABY CARE", 2: "BEAUTY", 3: "BEVERAGES", 4: "BOOKS",
    5: "BREAD/BAKERY", 6: "CELEBRATION", 7: "CLEANING", 8: "DAIRY", 9: "DELI",
    10: "EGGS", 11: "FROZEN FOODS", 12: "GROCERY I", 13: "GROCERY II",
    14: "HARDWARE", 15: "HOME AND KITCHEN I", 16: "HOME AND KITCHEN II",
    17: "HOME APPLIANCES", 18: "HOME CARE", 19: "LADIESWEAR",
    20: "LAWN AND GARDEN", 21: "LINGERIE", 22: "LIQUOR,WINE,BEER",
    23: "MAGAZINES", 24: "MEATS", 25: "PERSONAL CARE",
    26: "PET SUPPLIES", 27: "PLAYERS AND ELECTRONICS", 28: "POULTRY",
    29: "PREPARED FOODS", 30: "PRODUCE", 31: "SCHOOL AND OFFICE SUPPLIES",
    32: "SEAFOOD",
}
# Verified directly against models/family_encoder.pkl (LabelEncoder.classes_).

# ---------------------------------------------------------
# Cached loaders
# ---------------------------------------------------------
@st.cache_resource
def load_model():
    with open(MODEL_PATH, "rb") as f:
        return pickle.load(f)


@st.cache_data
def load_data():
    df = pd.read_csv(DATA_PATH, parse_dates=["date"])
    return df


@st.cache_data
def load_comparison():
    return pd.read_csv(COMPARISON_PATH)


@st.cache_data
def load_text_artifact(path):
    if not os.path.exists(path):
        return None
    with open(path, "r") as f:
        return f.read()


@st.cache_data
def load_json_artifact(path):
    if not os.path.exists(path):
        return None
    with open(path, "r") as f:
        return json.load(f)


@st.cache_data
def load_csv_artifact(path):
    if not os.path.exists(path):
        return None
    return pd.read_csv(path, parse_dates=["date"] if "date" in pd.read_csv(path, nrows=0).columns else None)


# ---------------------------------------------------------
# Load with error handling
# ---------------------------------------------------------
try:
    model = load_model()
except Exception as e:
    st.error(f"Could not load model from `{MODEL_PATH}`: {e}")
    st.stop()

try:
    df = load_data()
except Exception as e:
    st.error(f"Could not load data from `{DATA_PATH}`: {e}")
    st.stop()

missing_cols = [c for c in MODEL_FEATURES if c not in df.columns]
if missing_cols:
    st.error(f"feature_store.csv is missing columns the model needs: {missing_cols}")
    st.stop()

# ---------------------------------------------------------
# Header
# ---------------------------------------------------------
st.title("📈 Corporación Favorita — Sales Forecasting")
st.caption(
    "Classical baselines (ARIMA, SARIMA, Prophet) and a LightGBM model, "
    "compared on a granularity-consistent basis, plus a SHAP explainability "
    "layer for the LightGBM model. Deep learning models (LSTM / TFT / "
    "N-BEATS) are still in progress."
)

date_min = df["date"].min().date()
date_max = df["date"].max().date()
st.info(
    f"Data window shown: **{date_min} → {date_max}** ({len(df):,} rows, "
    f"{df['store_nbr'].nunique()} stores × {df['family'].nunique()} product families). "
    "This is a trimmed sample bundled with the repo for size reasons — the "
    "classical-model diagnostics below are exported from the notebook, which "
    "trains on the full multi-year national series."
)

tab_explore, tab_categories, tab_classical, tab_shap, tab_compare = st.tabs(
    ["🔎 Forecast Explorer", "🗂️ Category Trends", "📐 Classical Models", "🧠 SHAP & Anomalies", "📊 Model Comparison"]
)

# ===========================================================
# TAB 1 — Interactive forecast explorer (store / family)
# ===========================================================
with tab_explore:
    st.header("Explore a Store / Product Family")

    col1, col2 = st.columns(2)
    with col1:
        store = st.selectbox("Store number", sorted(df["store_nbr"].unique()), key="explore_store")
    with col2:
        family_options = sorted(df["family"].unique())
        family = st.selectbox(
            "Product family",
            family_options,
            format_func=lambda code: FAMILY_NAMES.get(code, f"Family {code}"),
            key="explore_family",
        )

    subset = df[(df["store_nbr"] == store) & (df["family"] == family)].sort_values("date")

    if subset.empty:
        st.warning("No data available for this store / family combination in the current window.")
    else:
        X = subset[MODEL_FEATURES].apply(pd.to_numeric, errors="coerce").astype(float)
        if X.isna().any().any():
            bad_cols = X.columns[X.isna().any()].tolist()
            st.error(f"Non-numeric values found in columns: {bad_cols}. Check feature_store.csv for stray text/blank cells in these columns.")
            st.stop()
        preds = model.predict(X)

        fig = go.Figure()
        fig.add_trace(go.Scatter(x=subset["date"], y=subset["sales"], name="Actual",
                                  line=dict(color="#1f77b4", width=2)))
        fig.add_trace(go.Scatter(x=subset["date"], y=preds, name="LightGBM Predicted",
                                  line=dict(color="#ff7f0e", width=2, dash="dash")))
        fig.update_layout(
            title=f"Store {store} — {FAMILY_NAMES.get(family, f'Family {family}')}",
            xaxis_title="Date", yaxis_title="Sales", height=450,
            legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
        )
        st.plotly_chart(fig, use_container_width=True)

        mae = float(np.mean(np.abs(subset["sales"] - preds)))
        rmse = float(np.sqrt(np.mean((subset["sales"] - preds) ** 2)))
        m1, m2, m3 = st.columns(3)
        m1.metric("MAE (this slice)", f"{mae:,.2f}")
        m2.metric("RMSE (this slice)", f"{rmse:,.2f}")
        m3.metric("Avg. daily sales", f"{subset['sales'].mean():,.2f}")

# ===========================================================
# TAB 2 — Overall sales across ALL stores, multiple categories
# ===========================================================
with tab_categories:
    st.header("Sales by Category, Summed Across All Stores")
    st.caption(
        "Every store is aggregated together here — the comparison is purely "
        "across product families over time."
    )

    family_totals = (
        df.groupby("family")["sales"].sum().sort_values(ascending=False)
    )
    default_families = family_totals.head(5).index.tolist()

    selected_families = st.multiselect(
        "Product families to compare",
        options=sorted(df["family"].unique()),
        default=default_families,
        format_func=lambda code: FAMILY_NAMES.get(code, f"Family {code}"),
    )
    show_total = st.checkbox("Also show combined total of selected families", value=False)

    if not selected_families:
        st.info("Pick at least one product family above.")
    else:
        cat_df = (
            df[df["family"].isin(selected_families)]
            .groupby(["date", "family"])["sales"]
            .sum()
            .reset_index()
        )
        cat_df["family_name"] = cat_df["family"].map(lambda c: FAMILY_NAMES.get(c, f"Family {c}"))

        fig = px.line(
            cat_df.sort_values("date"),
            x="date", y="sales", color="family_name", markers=True,
            labels={"sales": "Total sales (all stores)", "date": "Date", "family_name": "Family"},
        )

        if show_total:
            total_series = cat_df.groupby("date")["sales"].sum().reset_index()
            fig.add_trace(go.Scatter(
                x=total_series["date"], y=total_series["sales"],
                name="Selected — Combined Total",
                line=dict(color="black", width=3, dash="dot"),
            ))

        fig.update_layout(height=500, legend=dict(orientation="h", yanchor="bottom", y=1.02))
        st.plotly_chart(fig, use_container_width=True)

        st.caption(
            "Top families by total sales in this data window: "
            + ", ".join(f"{FAMILY_NAMES.get(c, c)}" for c in family_totals.head(8).index)
        )

# ===========================================================
# TAB 3 — ARIMA / SARIMA / Prophet summaries
# ===========================================================
with tab_classical:
    st.header("Classical Model Diagnostics")
    st.caption(
        "ARIMA, SARIMA, and Prophet were all refit on the same national daily "
        "aggregate for a granularity-consistent comparison. These summaries "
        "are exported once from the notebook (full multi-year series) rather "
        "than re-fit here, since the sample data bundled with this app is "
        "only a few weeks long."
    )

    arima_summary = load_text_artifact(ARIMA_SUMMARY_PATH)
    sarima_summary = load_text_artifact(SARIMA_SUMMARY_PATH)
    prophet_summary = load_json_artifact(PROPHET_SUMMARY_PATH)
    arima_fc = load_csv_artifact(ARIMA_FORECAST_PATH)
    sarima_fc = load_csv_artifact(SARIMA_FORECAST_PATH)
    prophet_fc = load_csv_artifact(PROPHET_FORECAST_PATH)

    have_any_forecast = any(x is not None for x in (arima_fc, sarima_fc, prophet_fc))

    if have_any_forecast:
        st.subheader("Test-window forecasts vs. actual (national daily sales)")
        fig = go.Figure()
        base = next(x for x in (arima_fc, sarima_fc, prophet_fc) if x is not None)
        if "actual" in base.columns:
            fig.add_trace(go.Scatter(x=base["date"], y=base["actual"], name="Actual",
                                      line=dict(color="black", width=2)))
        for name, fc, color in [
            ("ARIMA", arima_fc, "#1f77b4"),
            ("SARIMA", sarima_fc, "#2ca02c"),
            ("Prophet", prophet_fc, "#d62728"),
        ]:
            if fc is not None:
                y_col = "predicted" if "predicted" in fc.columns else "yhat"
                if y_col in fc.columns:
                    fig.add_trace(go.Scatter(x=fc["date"], y=fc[y_col], name=name,
                                              line=dict(color=color, width=2, dash="dash")))
        fig.update_layout(height=450, xaxis_title="Date", yaxis_title="National daily sales")
        st.plotly_chart(fig, use_container_width=True)

    col_a, col_s, col_p = st.columns(3)

    with col_a:
        st.subheader("ARIMA")
        if arima_summary:
            with st.expander("Full statsmodels summary", expanded=False):
                st.code(arima_summary, language=None)
        else:
            st.info(f"`{ARIMA_SUMMARY_PATH}` not found yet — see export snippet below.")

    with col_s:
        st.subheader("SARIMA")
        if sarima_summary:
            with st.expander("Full statsmodels summary", expanded=False):
                st.code(sarima_summary, language=None)
        else:
            st.info(f"`{SARIMA_SUMMARY_PATH}` not found yet — see export snippet below.")

    with col_p:
        st.subheader("Prophet")
        if prophet_summary:
            st.write(f"**Growth:** {prophet_summary.get('growth', 'n/a')}")
            st.write(f"**Seasonalities:** {', '.join(prophet_summary.get('seasonalities', [])) or 'n/a'}")
            st.write(f"**Holidays modeled:** {prophet_summary.get('n_holidays', 'n/a')}")
            st.write(f"**Changepoints:** {prophet_summary.get('n_changepoints', 'n/a')}")
        else:
            st.info(f"`{PROPHET_SUMMARY_PATH}` not found yet — see export snippet below.")
        try:
            st.image(PROPHET_IMG, use_container_width=True, caption="Prophet components")
        except Exception:
            pass

    if not (arima_summary and sarima_summary and prophet_summary):
        with st.expander("📋 How to generate these artifacts from the notebook"):
            st.markdown(
                "Run this after fitting each model on the national aggregate "
                "(same cell that builds `national_classical_df`), then commit "
                "the output files under `reports/`:"
            )
            st.code(
                '''# --- ARIMA / SARIMA text summaries ---
with open("reports/arima_summary.txt", "w") as f:
    f.write(str(arima_model.summary()))
with open("reports/sarima_summary.txt", "w") as f:
    f.write(str(sarima_model.summary()))

# --- Prophet summary (Prophet objects aren't easily pickled/displayed) ---
import json
prophet_summary = {
    "growth": m_holidays.growth,
    "seasonalities": list(m_holidays.seasonalities.keys()),
    "n_holidays": len(m_holidays.holidays) if m_holidays.holidays is not None else 0,
    "n_changepoints": len(m_holidays.changepoints),
}
with open("reports/prophet_summary.json", "w") as f:
    json.dump(prophet_summary, f, indent=2)

# --- Forecast vs actual on the shared test window (for the overlay chart) ---
pd.DataFrame({"date": test.index, "actual": test.values,
              "predicted": arima_forecast.values}).to_csv("reports/arima_forecast.csv", index=False)
pd.DataFrame({"date": test.index, "actual": test.values,
              "predicted": sarima_forecast.values}).to_csv("reports/sarima_forecast.csv", index=False)
prophet_fc_test = m_holidays.predict(prophet_test[["ds"]])
pd.DataFrame({"date": prophet_test["ds"], "actual": prophet_test["y"].values,
              "yhat": prophet_fc_test["yhat"].values}).to_csv("reports/prophet_forecast.csv", index=False)''',
                language="python",
            )

# ===========================================================
# TAB 4 — SHAP explainability + anomaly explanations
# ===========================================================
with tab_shap:
    st.header("SHAP Explainability")

    try:
        import shap
    except ImportError:
        st.error("The `shap` package isn't installed. Add `shap` to requirements.txt.")
        st.stop()

    @st.cache_resource
    def get_explainer(_model):
        return shap.TreeExplainer(_model)

    @st.cache_data
    def get_shap_sample(_df, sample_size=500, seed=42):
        clean = _df.dropna(subset=MODEL_FEATURES)
        n = min(sample_size, len(clean))
        sample = clean.sample(n=n, random_state=seed)
        X_sample = sample[MODEL_FEATURES].apply(pd.to_numeric, errors="coerce").astype(float)
        return sample, X_sample

    explainer = get_explainer(model)
    sample_rows, X_sample = get_shap_sample(df)

    with st.spinner("Computing SHAP values on a 500-row sample…"):
        shap_values_sample = explainer.shap_values(X_sample)

    st.subheader("Global feature impact")
    mean_abs_shap = np.abs(shap_values_sample).mean(axis=0)
    importance_df = pd.DataFrame({
        "feature": MODEL_FEATURES,
        "label": [FEATURE_LABELS.get(f, f) for f in MODEL_FEATURES],
        "mean_abs_shap": mean_abs_shap,
    }).sort_values("mean_abs_shap", ascending=True).tail(15)

    fig_imp = go.Figure(go.Bar(
        x=importance_df["mean_abs_shap"], y=importance_df["label"],
        orientation="h", marker_color="#636EFA",
    ))
    fig_imp.update_layout(height=500, xaxis_title="Mean |SHAP value| (impact on predicted sales)",
                           yaxis_title="")
    st.plotly_chart(fig_imp, use_container_width=True)

    st.divider()

    # -------------------------------------------------------
    # Anomaly explanations
    # -------------------------------------------------------
    st.subheader("Why was this flagged as an anomaly?")

    if "is_anomaly" not in df.columns or df["is_anomaly"].sum() == 0:
        st.info("No rows are flagged with `is_anomaly = 1` in the current data window.")
    else:
        anomalies = df[df["is_anomaly"] == 1].copy()
        st.caption(f"{len(anomalies):,} rows are flagged as anomalies in this data window.")

        max_options = 300
        if len(anomalies) > max_options:
            anomalies_display = anomalies.sample(n=max_options, random_state=1).sort_values("date")
            st.caption(f"Showing a random sample of {max_options} for the picker below.")
        else:
            anomalies_display = anomalies.sort_values("date")

        anomalies_display = anomalies_display.reset_index(drop=True)
        anomalies_display["label"] = anomalies_display.apply(
            lambda r: f"{r['date'].date()} — Store {int(r['store_nbr'])} — "
                      f"{FAMILY_NAMES.get(int(r['family']), r['family'])} — actual sales {r['sales']:.1f}",
            axis=1,
        )

        chosen_label = st.selectbox("Pick a flagged anomaly to explain", anomalies_display["label"])
        chosen_row = anomalies_display[anomalies_display["label"] == chosen_label].iloc[0]

        row_X = chosen_row[MODEL_FEATURES].apply(pd.to_numeric, errors="coerce").astype(float)
        row_X_df = pd.DataFrame([row_X.values], columns=MODEL_FEATURES)

        row_shap = explainer.shap_values(row_X_df)[0]
        base_value = explainer.expected_value
        if isinstance(base_value, (list, np.ndarray)):
            base_value = base_value[0]
        predicted = base_value + row_shap.sum()

        m1, m2, m3 = st.columns(3)
        m1.metric("Actual sales", f"{chosen_row['sales']:.1f}")
        m2.metric("Model predicted", f"{predicted:.1f}")
        m3.metric("Baseline (avg. prediction)", f"{base_value:.1f}")

        contrib_df = pd.DataFrame({
            "feature": MODEL_FEATURES,
            "label": [FEATURE_LABELS.get(f, f) for f in MODEL_FEATURES],
            "value": row_X.values,
            "shap": row_shap,
        })
        contrib_df["abs_shap"] = contrib_df["shap"].abs()
        top_contrib = contrib_df.sort_values("abs_shap", ascending=False).head(8)

        fig_wf = go.Figure(go.Bar(
            x=top_contrib.sort_values("shap")["shap"],
            y=top_contrib.sort_values("shap")["label"],
            orientation="h",
            marker_color=["#d62728" if v < 0 else "#2ca02c" for v in top_contrib.sort_values("shap")["shap"]],
        ))
        fig_wf.update_layout(
            height=400, xaxis_title="SHAP contribution (push toward higher / lower sales)",
            yaxis_title="", title="Top drivers for this prediction",
        )
        st.plotly_chart(fig_wf, use_container_width=True)

        st.markdown("**In plain terms:**")
        narrative_top = contrib_df.sort_values("abs_shap", ascending=False).head(4)
        bullets = []
        for _, r in narrative_top.iterrows():
            direction = "pushed the prediction **up**" if r["shap"] > 0 else "pushed the prediction **down**"
            bullets.append(
                f"- **{r['label']}** (value: {r['value']:.2f}) {direction} by about {abs(r['shap']):.1f} units."
            )
        st.markdown("\n".join(bullets))

        residual = chosen_row["sales"] - predicted
        if abs(residual) > 0.1 * max(abs(predicted), 1):
            st.caption(
                f"Note: the model's prediction still misses the actual value by "
                f"~{residual:.1f} units — the flagged features above explain the "
                "model's prediction, not necessarily why the true sales spiked/dropped."
            )

# ===========================================================
# TAB 5 — Model comparison summary
# ===========================================================
with tab_compare:
    st.header("Model Comparison So Far")
    try:
        comp = load_comparison()
        st.dataframe(comp, use_container_width=True)

        if "MAE" in comp.columns and comp["MAE"].max() / max(comp["MAE"].min(), 1e-9) > 100:
            st.caption(
                "⚠️ MAE values span more than two orders of magnitude across rows — "
                "that's usually a sign some rows were fit on a different granularity "
                "(e.g. national aggregate vs. single store-family). Worth double-checking "
                "before treating this table as a like-for-like comparison."
            )
    except FileNotFoundError:
        st.info(f"`{COMPARISON_PATH}` not found in the repo.")
    except Exception as e:
        st.warning(f"Could not load model comparison table: {e}")

    c1, c2 = st.columns(2)
    with c1:
        st.subheader("LightGBM Feature Importance")
        try:
            st.image(FEATURE_IMPORTANCE_IMG, use_container_width=True)
        except Exception:
            st.info("Feature importance image not found.")
    with c2:
        st.subheader("Prophet Components")
        try:
            st.image(PROPHET_IMG, use_container_width=True)
        except Exception:
            st.info("Prophet components image not found.")

st.divider()
st.caption(
    "Built as an interim checkpoint for a 38-day sales forecasting project on the "
    "Corporación Favorita Kaggle dataset. Repo: "
    "[github.com/Elite407/sales-forecasting](https://github.com/Elite407/sales-forecasting)"
)
