import json
import os
import warnings

import numpy as np
import pandas as pd
import pickle
import plotly.graph_objects as go
import plotly.express as px
import streamlit as st
from sklearn.feature_extraction.text import TfidfVectorizer

# NEW deps for the GenAI Analyst tab (6th tab, added below):
#   - add `google-genai` and `scikit-learn` to requirements.txt
#   - set GEMINI_API_KEY in .streamlit/secrets.toml (local) or the Streamlit Cloud
#     app's Secrets settings (deployed). Free key: https://aistudio.google.com/apikey

warnings.filterwarnings("ignore")

st.set_page_config(page_title="Favorita Sales Forecasting", layout="wide", page_icon="📈")

# ---------------------------------------------------------
# Paths (relative to repo root — Streamlit Cloud runs from there)
# ---------------------------------------------------------
MODEL_PATH = "models/lgbm_model.pkl"
DATA_PATH = "data/processed/feature_store.csv"
COMPARISON_PATH = "reports/model_comparison_table.csv"
FEATURE_IMPORTANCE_IMG = "reports/lgbm_feature_importance.png"
PROPHET_IMG = "reports/prophet_components_holidays.png"

# Precomputed classical-model artifacts. These are NOT generated by this app —
# they're exported once from the notebook (on the full multi-year national
# series) and committed to the repo. See the "export_artifacts" snippet in the
# notebook / README for how to regenerate them.
ARIMA_SUMMARY_PATH = "reports/arima_summary.txt"
SARIMA_SUMMARY_PATH = "reports/sarima_summary.txt"
PROPHET_SUMMARY_PATH = "reports/prophet_summary.json"
ARIMA_FORECAST_PATH = "reports/arima_forecast.csv"
SARIMA_FORECAST_PATH = "reports/sarima_forecast.csv"
PROPHET_FORECAST_PATH = "reports/prophet_forecast.csv"

# Exact feature order the trained LightGBM Booster expects.
# (Verified directly against the model with model.feature_name() —
# do not reorder or rename these.)
# NOTE: `is_anomaly` sits in this list because that's how the pickled model
# was trained. Worth flagging: if `is_anomaly` is derived from the sales
# value itself, it's a leakage risk for a live forecasting feature — fine for
# this diagnostic dashboard (we already know the label), but don't reuse this
# feature list for a true forward forecast without checking how it's built.
MODEL_FEATURES = [
    "day_of_week", "month", "is_weekend", "is_month_start", "is_month_end",
    "month_sin", "month_cos", "dow_sin", "dow_cos",
    "sales_lag_1", "sales_lag_7", "sales_lag_14", "sales_lag_28",
    "rolling_mean_7", "rolling_mean_28", "rolling_std_7", "rolling_std_28",
    "expanding_mean_sales", "dcoilwtico",
    "promo_lag_1", "promo_lag_7", "promo_rolling_mean_7",
    "is_holiday", "is_national_holiday", "days_to_next_holiday", "is_anomaly",
]

# Plain-English labels used in the SHAP anomaly narrative below.
FEATURE_LABELS = {
    "day_of_week": "day of the week",
    "month": "month of year",
    "is_weekend": "weekend flag",
    "is_month_start": "start-of-month flag",
    "is_month_end": "end-of-month flag",
    "month_sin": "seasonal month position (sin)",
    "month_cos": "seasonal month position (cos)",
    "dow_sin": "seasonal weekday position (sin)",
    "dow_cos": "seasonal weekday position (cos)",
    "sales_lag_1": "sales 1 day earlier",
    "sales_lag_7": "sales 7 days earlier (same weekday)",
    "sales_lag_14": "sales 14 days earlier",
    "sales_lag_28": "sales 28 days earlier",
    "rolling_mean_7": "7-day rolling average sales",
    "rolling_mean_28": "28-day rolling average sales",
    "rolling_std_7": "7-day sales volatility",
    "rolling_std_28": "28-day sales volatility",
    "expanding_mean_sales": "all-time average sales to date",
    "dcoilwtico": "oil price (WTI)",
    "promo_lag_1": "on-promotion flag, 1 day earlier",
    "promo_lag_7": "on-promotion flag, 7 days earlier",
    "promo_rolling_mean_7": "7-day rolling promo intensity",
    "is_holiday": "local/regional holiday flag",
    "is_national_holiday": "national holiday flag",
    "days_to_next_holiday": "days until next holiday",
    "is_anomaly": "flagged-anomaly indicator",
}

FAMILY_NAMES = {
    0: "AUTOMOTIVE", 1: "BABY CARE", 2: "BEAUTY", 3: "BEVERAGES", 4: "BOOKS",
    5: "BREAD/BAKERY", 6: "CELEBRATION", 7: "CLEANING", 8: "DAIRY", 9: "DELI",
    10: "EGGS", 11: "FROZEN FOODS", 12: "GROCERY I", 13: "GROCERY II",
    14: "HARDWARE", 15: "HOME AND KITCHEN I", 16: "HOME AND KITCHEN II",
    17: "HOME APPLIANCES", 18: "HOME CARE", 19: "LADIESWEAR",
    20: "LAWN AND GARDEN", 21: "LINGERIE", 22: "LIQUOR,WINE,BEER",
    23: "MAGAZINES", 24: "MEATS", 25: "PERSONAL CARE",
    26: "PET SUPPLIES", 27: "PLAYERS AND ELECTRONICS", 28: "POULTRY",
    29: "PREPARED FOODS", 30: "PRODUCE", 31: "SCHOOL AND OFFICE SUPPLIES",
    32: "SEAFOOD",
}
# Verified directly against models/family_encoder.pkl (LabelEncoder.classes_).

# ---------------------------------------------------------
# Cached loaders
# ---------------------------------------------------------
@st.cache_resource
def load_model():
    with open(MODEL_PATH, "rb") as f:
        return pickle.load(f)


@st.cache_data
def load_data():
    df = pd.read_csv(DATA_PATH, parse_dates=["date"])
    return df


@st.cache_data
def load_comparison():
    return pd.read_csv(COMPARISON_PATH)


@st.cache_data
def load_text_artifact(path):
    if not os.path.exists(path):
        return None
    with open(path, "r") as f:
        return f.read()


@st.cache_data
def load_json_artifact(path):
    if not os.path.exists(path):
        return None
    with open(path, "r") as f:
        return json.load(f)


@st.cache_data
def load_csv_artifact(path):
    if not os.path.exists(path):
        return None
    return pd.read_csv(path, parse_dates=["date"] if "date" in pd.read_csv(path, nrows=0).columns else None)


# ---------------------------------------------------------
# Load with error handling
# ---------------------------------------------------------
try:
    model = load_model()
except Exception as e:
    st.error(f"Could not load model from `{MODEL_PATH}`: {e}")
    st.stop()

try:
    df = load_data()
except Exception as e:
    st.error(f"Could not load data from `{DATA_PATH}`: {e}")
    st.stop()

missing_cols = [c for c in MODEL_FEATURES if c not in df.columns]
if missing_cols:
    st.error(f"feature_store.csv is missing columns the model needs: {missing_cols}")
    st.stop()

# ===========================================================
# GenAI Analyst — knowledge base, tool functions, agent loop
# (backs the 6th tab, defined further down). Kept self-contained and defensive
# so a missing package or API key degrades gracefully instead of breaking the
# rest of the app.
# ===========================================================

# --- Domain knowledge base for retrieval (RAG). TF-IDF, not embeddings — this
# stays a few KB and avoids pulling PyTorch into the Streamlit Cloud deploy. ---
GENAI_KNOWLEDGE_BASE = [
    "On April 16, 2016, a 7.8-magnitude earthquake struck Ecuador near Pedernales. "
    "Relief efforts in the following weeks led people to donate water and other "
    "essential goods, which significantly affected supermarket sales nationally "
    "for several weeks after the earthquake.",

    "Ecuador's economy is oil-dependent and WTI oil prices collapsed from over "
    "$100/barrel in mid-2014 to under $30/barrel by early 2016, straining "
    "government spending and consumer demand through much of the sample period.",

    "Holidays in this dataset are typed as Local, Regional, or National in scope, "
    "and some are 'transferred' to a different date than their traditional one, or "
    "marked as a 'Bridge' day added to extend a holiday, or a 'Work Day' that makes "
    "up for a bridge day elsewhere — the transferred date is the one that actually "
    "affects sales, not the traditional date.",

    "Public sector wages in Ecuador are paid on the 15th and on the last day of "
    "each month, which tends to produce a recurring sales bump in the days "
    "immediately following those paydays.",

    "Ecuador has used the US dollar as its official currency since 2000, so sales "
    "figures in this dataset are not affected by local currency devaluation risk "
    "the way some other Latin American retail datasets can be.",

    "The 'onpromotion' signal indicates how many items in a product family were "
    "on promotion on a given day; promo intensity is one of the stronger drivers "
    "the LightGBM model picks up in SHAP, alongside recent lag and rolling-mean sales.",

    "December is the strongest seasonal period in this dataset across most "
    "product families, especially GROCERY, BEVERAGES, and LIQUOR/WINE/BEER, "
    "consistent with Christmas and New Year retail demand.",

    "Rows flagged `is_anomaly = 1` in this pipeline are statistically detected "
    "outliers (unusually large deviations from recent rolling behavior), not "
    "confirmed data-quality errors — a flagged spike can reflect a real event "
    "(like the earthquake or a big promotion) rather than a mistake in the data.",

    "LightGBM in this project is trained at row level (store x product family x "
    "day), while ARIMA, SARIMA, and Prophet are all fit on the national daily "
    "aggregate — so their error metrics are not directly comparable on a like-for-"
    "like basis without accounting for that granularity difference.",

    "Back-to-school shopping season in Ecuador falls at different times in "
    "different regions — around April-May on the coast and around August-"
    "September in the highlands — which can show up as regional demand bumps "
    "in school/office supplies and related categories that a national-only "
    "model would smooth over.",
]


@st.cache_resource
def _get_genai_kb_index():
    vectorizer = TfidfVectorizer(stop_words="english")
    doc_matrix = vectorizer.fit_transform(GENAI_KNOWLEDGE_BASE)
    return vectorizer, doc_matrix


def genai_retrieve_context(query, k=3):
    vectorizer, doc_matrix = _get_genai_kb_index()
    q_vec = vectorizer.transform([query])
    sims = (doc_matrix @ q_vec.T).toarray().ravel()
    top_idx = sims.argsort()[::-1][:k]
    return [GENAI_KNOWLEDGE_BASE[i] for i in top_idx if sims[i] > 0]


# --- SHAP explainer for the GenAI tool, independent of the SHAP tab below so
# this tab still works even if that tab's own setup changes. ---
try:
    import shap as _genai_shap

    @st.cache_resource
    def _get_genai_shap_explainer(_model):
        return _genai_shap.TreeExplainer(_model)

    _GENAI_SHAP_AVAILABLE = True
except ImportError:
    _GENAI_SHAP_AVAILABLE = False


# --- Tool functions: these are what the LLM can actually call. Every number
# the agent states should trace back to one of these — nothing is invented. ---
def _tool_get_model_comparison(**_):
    try:
        comp = load_comparison()
        return comp.to_dict(orient="records")
    except Exception as e:
        return {"error": f"Could not load model comparison table: {e}"}


def _tool_get_shap_drivers(store=None, family=None, date=None, **_):
    if not _GENAI_SHAP_AVAILABLE:
        return {"error": "The `shap` package isn't installed in this environment."}
    try:
        target_date = pd.to_datetime(date)
    except Exception:
        return {"error": f"Could not parse date '{date}'. Use YYYY-MM-DD format."}

    row = df[(df["store_nbr"] == store) & (df["family"] == family) & (df["date"] == target_date)]
    if row.empty:
        return {
            "error": (
                f"No row found for store={store}, family={family}, date={date} in the "
                f"loaded data window ({df['date'].min().date()} to {df['date'].max().date()})."
            )
        }
    row = row.iloc[0]
    X_row = row[MODEL_FEATURES].apply(pd.to_numeric, errors="coerce").astype(float)
    X_row_df = pd.DataFrame([X_row.values], columns=MODEL_FEATURES)

    explainer = _get_genai_shap_explainer(model)
    shap_vals = explainer.shap_values(X_row_df)[0]
    contrib = sorted(zip(MODEL_FEATURES, shap_vals), key=lambda t: -abs(t[1]))[:5]

    return {
        "actual_sales": float(row["sales"]),
        "top_drivers": [
            {"feature": FEATURE_LABELS.get(f, f), "shap_contribution": round(float(v), 2)}
            for f, v in contrib
        ],
    }


def _tool_get_anomalies(store=None, family=None, **_):
    subset = df[(df["store_nbr"] == store) & (df["family"] == family) & (df["is_anomaly"] == 1)]
    if subset.empty:
        return {"anomaly_dates": [], "note": "No flagged anomalies for this store/family in the loaded window."}
    return {"anomaly_dates": subset[["date", "sales"]].astype(str).to_dict(orient="records")}


def _tool_get_forecast_metrics(store=None, family=None, **_):
    subset = df[(df["store_nbr"] == store) & (df["family"] == family)].sort_values("date")
    if subset.empty:
        return {"error": "No data for this store/family in the loaded window."}
    X = subset[MODEL_FEATURES].apply(pd.to_numeric, errors="coerce").astype(float)
    preds = model.predict(X)
    mae = float(np.mean(np.abs(subset["sales"] - preds)))
    rmse = float(np.sqrt(np.mean((subset["sales"] - preds) ** 2)))
    return {
        "store": store,
        "family": FAMILY_NAMES.get(family, family),
        "mae": round(mae, 2),
        "rmse": round(rmse, 2),
        "avg_daily_sales": round(float(subset["sales"].mean()), 2),
        "n_days": int(len(subset)),
    }


def _tool_search_context(query=None, **_):
    return {"context_snippets": genai_retrieve_context(query or "")}


GENAI_FUNCTIONS = {
    "get_model_comparison": _tool_get_model_comparison,
    "get_shap_drivers": _tool_get_shap_drivers,
    "get_anomalies": _tool_get_anomalies,
    "get_forecast_metrics": _tool_get_forecast_metrics,
    "search_context": _tool_search_context,
}

GENAI_TOOLS = [
    {
        "type": "function",
        "name": "get_model_comparison",
        "description": "Returns the model comparison table (error metrics per model, e.g. ARIMA/SARIMA/Prophet/LightGBM) as a list of records.",
        "parameters": {"type": "object", "properties": {}, "required": []},
    },
    {
        "type": "function",
        "name": "get_shap_drivers",
        "description": (
            "Returns the actual sales value and the top SHAP feature contributions driving "
            "the LightGBM prediction for a specific store, product family, and date."
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "store": {"type": "integer", "description": "Store number, e.g. 3"},
                "family": {"type": "integer", "description": "Product family code (0-32) — see the code map in your instructions"},
                "date": {"type": "string", "description": "Date in YYYY-MM-DD format"},
            },
            "required": ["store", "family", "date"],
        },
    },
    {
        "type": "function",
        "name": "get_anomalies",
        "description": "Lists dates flagged as statistical sales anomalies for a specific store and product family.",
        "parameters": {
            "type": "object",
            "properties": {
                "store": {"type": "integer"},
                "family": {"type": "integer"},
            },
            "required": ["store", "family"],
        },
    },
    {
        "type": "function",
        "name": "get_forecast_metrics",
        "description": "Returns LightGBM prediction accuracy (MAE, RMSE, average daily sales) for a specific store and product family over the loaded data window.",
        "parameters": {
            "type": "object",
            "properties": {
                "store": {"type": "integer"},
                "family": {"type": "integer"},
            },
            "required": ["store", "family"],
        },
    },
    {
        "type": "function",
        "name": "search_context",
        "description": (
            "Searches a knowledge base of real-world context about this dataset (the 2016 "
            "Ecuador earthquake, oil price shocks, holiday calendar quirks, payday effects, "
            "etc.) for information relevant to a query."
        ),
        "parameters": {
            "type": "object",
            "properties": {"query": {"type": "string"}},
            "required": ["query"],
        },
    },
]

_GENAI_FAMILY_CODE_MAP = ", ".join(f"{code}={name}" for code, name in FAMILY_NAMES.items())

GENAI_SYSTEM_PROMPT = (
    "You are an analyst embedded in a retail demand-forecasting dashboard (Corporación "
    "Favorita Kaggle dataset). Only state numbers that come from a tool result — never "
    "estimate or invent sales figures, SHAP values, or error metrics. If a tool returns "
    "an error or no data, say so plainly rather than filling the gap yourself. If a "
    "question is unrelated to this forecasting project, politely decline. "
    f"Product family codes: {_GENAI_FAMILY_CODE_MAP}. When the user names a family in "
    "words (e.g. 'beverages'), map it to the matching numeric code before calling a tool."
)

try:
    from google import genai as _google_genai
    GENAI_SDK_AVAILABLE = True
except ImportError:
    GENAI_SDK_AVAILABLE = False

try:
    import openai as _openai
    GROQ_SDK_AVAILABLE = True
except ImportError:
    GROQ_SDK_AVAILABLE = False

def _get_groq_api_key():
    key = None
    try:
        key = st.secrets.get("GROQ_API_KEY")
    except Exception:
        pass
    return key or os.environ.get("GROQ_API_KEY")

@st.cache_data(show_spinner=False)
def generate_quick_insight_groq(selected_families_str, date_min_str, date_max_str, total_sales, leading_family, trend_direction):
    if not GROQ_SDK_AVAILABLE:
        return "The `openai` package isn't installed. Quick Insight is disabled."
    key = _get_groq_api_key()
    if not key:
        return "GROQ_API_KEY is missing from secrets.toml. Quick Insight is disabled."
    try:
        client = _openai.OpenAI(
            base_url="https://api.groq.com/openai/v1",
            api_key=key
        )
        prompt = (
            f"Write a 2-3 sentence plain-English caption summarizing these sales metrics for {selected_families_str} "
            f"between {date_min_str} and {date_max_str}:\n"
            f"- Total Sales: {total_sales:,.0f}\n"
            f"- Leading Family: {leading_family}\n"
            f"- Trend Direction: {trend_direction}\n"
            "Keep it professional and concise. Do not add any filler text."
        )
        response = client.chat.completions.create(
            model="openai/gpt-oss-20b",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.3
        )
        return response.choices[0].message.content.strip()
    except Exception as e:
        return f"Could not generate Quick Insight via Groq API: {e}"


def _get_gemini_api_key():
    key = None
    try:
        key = st.secrets.get("GEMINI_API_KEY")
    except Exception:
        pass
    return key or os.environ.get("GEMINI_API_KEY")


@st.cache_resource
def get_genai_client(api_key):
    return _google_genai.Client(api_key=api_key)


def run_genai_agent(client, user_message, previous_interaction_id=None,
                     model="gemini-3.6-flash", max_rounds=5):
    """One user turn of the agent loop: calls the model, executes any tool calls
    it asks for, and keeps going (up to max_rounds) until it returns plain text."""
    tool_log = []
    interaction = client.interactions.create(
        model=model,
        system_instruction=GENAI_SYSTEM_PROMPT,
        tools=GENAI_TOOLS,
        input=user_message,
        previous_interaction_id=previous_interaction_id,
    )

    for _ in range(max_rounds):
        fc_steps = [s for s in interaction.steps if s.type == "function_call"]
        if not fc_steps:
            return interaction.output_text, tool_log, interaction.id

        function_results = []
        for step in fc_steps:
            fn = GENAI_FUNCTIONS.get(step.name)
            result = fn(**step.arguments) if fn else {"error": f"Unknown tool '{step.name}'"}
            tool_log.append({"tool": step.name, "input": step.arguments, "result": result})
            function_results.append({
                "type": "function_result",
                "name": step.name,
                "call_id": step.id,
                "result": [{"type": "text", "text": json.dumps(result, default=str)}],
            })

        interaction = client.interactions.create(
            model=model,
            tools=GENAI_TOOLS,
            previous_interaction_id=interaction.id,
            input=function_results,
        )

    return "Ran out of tool-call rounds — try a more specific question.", tool_log, interaction.id


# ---------------------------------------------------------
# Header
# ---------------------------------------------------------
st.title("📈 Corporación Favorita — Sales Forecasting")
st.caption(
    "Classical baselines (ARIMA, SARIMA, Prophet) and a LightGBM model, "
    "compared on a granularity-consistent basis, plus a SHAP explainability "
    "layer for the LightGBM model. Deep learning models (LSTM / TFT / "
    "N-BEATS) are still in progress."
)

date_min = df["date"].min().date()
date_max = df["date"].max().date()
st.info(
    f"Data window shown: **{date_min} → {date_max}** ({len(df):,} rows, "
    f"{df['store_nbr'].nunique()} stores × {df['family'].nunique()} product families). "
    "This is a trimmed sample bundled with the repo for size reasons — the "
    "classical-model diagnostics below are exported from the notebook, which "
    "trains on the full multi-year national series."
)

tab_explore, tab_categories, tab_classical, tab_shap, tab_compare, tab_genai = st.tabs(
    ["🔎 Forecast Explorer", "🗂️ Category Trends", "📐 Classical Models", "🧠 SHAP & Anomalies",
     "📊 Model Comparison", "🤖 GenAI Analyst"]
)

# ===========================================================
# TAB 1 — Interactive forecast explorer (store / family)
# ===========================================================
with tab_explore:
    st.header("Explore a Store / Product Family")

    col1, col2 = st.columns(2)
    with col1:
        store = st.selectbox("Store number", sorted(df["store_nbr"].unique()), key="explore_store")
    with col2:
        family_options = sorted(df["family"].unique())
        family = st.selectbox(
            "Product family",
            family_options,
            format_func=lambda code: FAMILY_NAMES.get(code, f"Family {code}"),
            key="explore_family",
        )

    subset = df[(df["store_nbr"] == store) & (df["family"] == family)].sort_values("date")

    if subset.empty:
        st.warning("No data available for this store / family combination in the current window.")
    else:
        X = subset[MODEL_FEATURES].apply(pd.to_numeric, errors="coerce").astype(float)
        if X.isna().any().any():
            bad_cols = X.columns[X.isna().any()].tolist()
            st.error(f"Non-numeric values found in columns: {bad_cols}. Check feature_store.csv for stray text/blank cells in these columns.")
            st.stop()
        preds = model.predict(X)

        fig = go.Figure()
        fig.add_trace(go.Scatter(x=subset["date"], y=subset["sales"], name="Actual",
                                  line=dict(color="#1f77b4", width=2)))
        fig.add_trace(go.Scatter(x=subset["date"], y=preds, name="LightGBM Predicted",
                                  line=dict(color="#ff7f0e", width=2, dash="dash")))
        fig.update_layout(
            title=f"Store {store} — {FAMILY_NAMES.get(family, f'Family {family}')}",
            xaxis_title="Date", yaxis_title="Sales", height=450,
            legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="right", x=1),
        )
        st.plotly_chart(fig, use_container_width=True)

        mae = float(np.mean(np.abs(subset["sales"] - preds)))
        rmse = float(np.sqrt(np.mean((subset["sales"] - preds) ** 2)))
        m1, m2, m3 = st.columns(3)
        m1.metric("MAE (this slice)", f"{mae:,.2f}")
        m2.metric("RMSE (this slice)", f"{rmse:,.2f}")
        m3.metric("Avg. daily sales", f"{subset['sales'].mean():,.2f}")

# ===========================================================
# TAB 2 — Overall sales across ALL stores, multiple categories
# ===========================================================
with tab_categories:
    st.header("Sales by Category, Summed Across All Stores")
    st.caption(
        "Every store is aggregated together here — the comparison is purely "
        "across product families over time."
    )

    family_totals = (
        df.groupby("family")["sales"].sum().sort_values(ascending=False)
    )
    default_families = family_totals.head(5).index.tolist()

    selected_families = st.multiselect(
        "Product families to compare",
        options=sorted(df["family"].unique()),
        default=default_families,
        format_func=lambda code: FAMILY_NAMES.get(code, f"Family {code}"),
    )
    show_total = st.checkbox("Also show combined total of selected families", value=False)

    if not selected_families:
        st.info("Pick at least one product family above.")
    else:
        cat_df = (
            df[df["family"].isin(selected_families)]
            .groupby(["date", "family"])["sales"]
            .sum()
            .reset_index()
        )
        cat_df["family_name"] = cat_df["family"].map(lambda c: FAMILY_NAMES.get(c, f"Family {c}"))

        fig = px.line(
            cat_df.sort_values("date"),
            x="date", y="sales", color="family_name", markers=True,
            labels={"sales": "Total sales (all stores)", "date": "Date", "family_name": "Family"},
        )

        if show_total:
            total_series = cat_df.groupby("date")["sales"].sum().reset_index()
            fig.add_trace(go.Scatter(
                x=total_series["date"], y=total_series["sales"],
                name="Selected — Combined Total",
                line=dict(color="black", width=3, dash="dot"),
            ))

        fig.update_layout(height=500, legend=dict(orientation="h", yanchor="bottom", y=1.02))
        st.plotly_chart(fig, use_container_width=True)

        st.caption(
            "Top families by total sales in this data window: "
            + ", ".join(f"{FAMILY_NAMES.get(c, c)}" for c in family_totals.head(8).index)
        )
        
        st.subheader("✨ Quick Insight")
        total_sales_selected = cat_df["sales"].sum()
        family_group = cat_df.groupby("family_name")["sales"].sum()
        leading_fam = family_group.idxmax() if not family_group.empty else "N/A"
        
        trend_series = cat_df.groupby("date")["sales"].sum().sort_index()
        if len(trend_series) > 1:
            mid = len(trend_series) // 2
            first_half = trend_series.iloc[:mid].mean()
            second_half = trend_series.iloc[mid:].mean()
            if second_half > first_half * 1.05:
                trend_dir = "Upward"
            elif second_half < first_half * 0.95:
                trend_dir = "Downward"
            else:
                trend_dir = "Stable"
        else:
            trend_dir = "Insufficient data"
            
        d_min = cat_df["date"].min().strftime('%Y-%m-%d') if not cat_df.empty else "N/A"
        d_max = cat_df["date"].max().strftime('%Y-%m-%d') if not cat_df.empty else "N/A"
        fams_str = ", ".join([FAMILY_NAMES.get(c, str(c)) for c in selected_families])
        
        with st.spinner("Generating insight..."):
            insight = generate_quick_insight_groq(
                fams_str, d_min, d_max,
                total_sales_selected, leading_fam, trend_dir
            )
        st.info(insight)

# ===========================================================
# TAB 3 — ARIMA / SARIMA / Prophet summaries
# ===========================================================
with tab_classical:
    st.header("Classical Model Diagnostics")
    st.caption(
        "ARIMA, SARIMA, and Prophet were all refit on the same national daily "
        "aggregate for a granularity-consistent comparison. These summaries "
        "are exported once from the notebook (full multi-year series) rather "
        "than re-fit here, since the sample data bundled with this app is "
        "only a few weeks long."
    )

    arima_summary = load_text_artifact(ARIMA_SUMMARY_PATH)
    sarima_summary = load_text_artifact(SARIMA_SUMMARY_PATH)
    prophet_summary = load_json_artifact(PROPHET_SUMMARY_PATH)
    arima_fc = load_csv_artifact(ARIMA_FORECAST_PATH)
    sarima_fc = load_csv_artifact(SARIMA_FORECAST_PATH)
    prophet_fc = load_csv_artifact(PROPHET_FORECAST_PATH)

    have_any_forecast = any(x is not None for x in (arima_fc, sarima_fc, prophet_fc))

    if have_any_forecast:
        st.subheader("Test-window forecasts vs. actual (national daily sales)")
        fig = go.Figure()
        base = next(x for x in (arima_fc, sarima_fc, prophet_fc) if x is not None)
        if "actual" in base.columns:
            fig.add_trace(go.Scatter(x=base["date"], y=base["actual"], name="Actual",
                                      line=dict(color="black", width=2)))
        for name, fc, color in [
            ("ARIMA", arima_fc, "#1f77b4"),
            ("SARIMA", sarima_fc, "#2ca02c"),
            ("Prophet", prophet_fc, "#d62728"),
        ]:
            if fc is not None:
                y_col = "predicted" if "predicted" in fc.columns else "yhat"
                if y_col in fc.columns:
                    fig.add_trace(go.Scatter(x=fc["date"], y=fc[y_col], name=name,
                                              line=dict(color=color, width=2, dash="dash")))
        fig.update_layout(height=450, xaxis_title="Date", yaxis_title="National daily sales")
        st.plotly_chart(fig, use_container_width=True)

    col_a, col_s, col_p = st.columns(3)

    with col_a:
        st.subheader("ARIMA")
        if arima_summary:
            with st.expander("Full statsmodels summary", expanded=False):
                st.code(arima_summary, language=None)
        else:
            st.info(f"`{ARIMA_SUMMARY_PATH}` not found yet — see export snippet below.")

    with col_s:
        st.subheader("SARIMA")
        if sarima_summary:
            with st.expander("Full statsmodels summary", expanded=False):
                st.code(sarima_summary, language=None)
        else:
            st.info(f"`{SARIMA_SUMMARY_PATH}` not found yet — see export snippet below.")

    with col_p:
        st.subheader("Prophet")
        if prophet_summary:
            st.write(f"**Growth:** {prophet_summary.get('growth', 'n/a')}")
            st.write(f"**Seasonalities:** {', '.join(prophet_summary.get('seasonalities', [])) or 'n/a'}")
            st.write(f"**Holidays modeled:** {prophet_summary.get('n_holidays', 'n/a')}")
            st.write(f"**Changepoints:** {prophet_summary.get('n_changepoints', 'n/a')}")
        else:
            st.info(f"`{PROPHET_SUMMARY_PATH}` not found yet — see export snippet below.")
        try:
            st.image(PROPHET_IMG, use_container_width=True, caption="Prophet components")
        except Exception:
            pass

    if not (arima_summary and sarima_summary and prophet_summary):
        with st.expander("📋 How to generate these artifacts from the notebook"):
            st.markdown(
                "Run this after fitting each model on the national aggregate "
                "(same cell that builds `national_classical_df`), then commit "
                "the output files under `reports/`:"
            )
            st.code(
                '''# --- ARIMA / SARIMA text summaries ---
with open("reports/arima_summary.txt", "w") as f:
    f.write(str(arima_model.summary()))
with open("reports/sarima_summary.txt", "w") as f:
    f.write(str(sarima_model.summary()))

# --- Prophet summary (Prophet objects aren't easily pickled/displayed) ---
import json
prophet_summary = {
    "growth": m_holidays.growth,
    "seasonalities": list(m_holidays.seasonalities.keys()),
    "n_holidays": len(m_holidays.holidays) if m_holidays.holidays is not None else 0,
    "n_changepoints": len(m_holidays.changepoints),
}
with open("reports/prophet_summary.json", "w") as f:
    json.dump(prophet_summary, f, indent=2)

# --- Forecast vs actual on the shared test window (for the overlay chart) ---
pd.DataFrame({"date": test.index, "actual": test.values,
              "predicted": arima_forecast.values}).to_csv("reports/arima_forecast.csv", index=False)
pd.DataFrame({"date": test.index, "actual": test.values,
              "predicted": sarima_forecast.values}).to_csv("reports/sarima_forecast.csv", index=False)
prophet_fc_test = m_holidays.predict(prophet_test[["ds"]])
pd.DataFrame({"date": prophet_test["ds"], "actual": prophet_test["y"].values,
              "yhat": prophet_fc_test["yhat"].values}).to_csv("reports/prophet_forecast.csv", index=False)''',
                language="python",
            )

# ===========================================================
# TAB 4 — SHAP explainability + anomaly explanations
# ===========================================================
with tab_shap:
    st.header("SHAP Explainability")

    try:
        import shap
    except ImportError:
        st.error("The `shap` package isn't installed. Add `shap` to requirements.txt.")
        st.stop()

    @st.cache_resource
    def get_explainer(_model):
        return shap.TreeExplainer(_model)

    @st.cache_data
    def get_shap_sample(_df, sample_size=500, seed=42):
        clean = _df.dropna(subset=MODEL_FEATURES)
        n = min(sample_size, len(clean))
        sample = clean.sample(n=n, random_state=seed)
        X_sample = sample[MODEL_FEATURES].apply(pd.to_numeric, errors="coerce").astype(float)
        return sample, X_sample

    explainer = get_explainer(model)
    sample_rows, X_sample = get_shap_sample(df)

    with st.spinner("Computing SHAP values on a 500-row sample…"):
        shap_values_sample = explainer.shap_values(X_sample)

    st.subheader("Global feature impact")
    mean_abs_shap = np.abs(shap_values_sample).mean(axis=0)
    importance_df = pd.DataFrame({
        "feature": MODEL_FEATURES,
        "label": [FEATURE_LABELS.get(f, f) for f in MODEL_FEATURES],
        "mean_abs_shap": mean_abs_shap,
    }).sort_values("mean_abs_shap", ascending=True).tail(15)

    fig_imp = go.Figure(go.Bar(
        x=importance_df["mean_abs_shap"], y=importance_df["label"],
        orientation="h", marker_color="#636EFA",
    ))
    fig_imp.update_layout(height=500, xaxis_title="Mean |SHAP value| (impact on predicted sales)",
                           yaxis_title="")
    st.plotly_chart(fig_imp, use_container_width=True)

    st.divider()

    # -------------------------------------------------------
    # Anomaly explanations
    # -------------------------------------------------------
    st.subheader("Why was this flagged as an anomaly?")

    if "is_anomaly" not in df.columns or df["is_anomaly"].sum() == 0:
        st.info("No rows are flagged with `is_anomaly = 1` in the current data window.")
    else:
        anomalies = df[df["is_anomaly"] == 1].copy()
        st.caption(f"{len(anomalies):,} rows are flagged as anomalies in this data window.")

        max_options = 300
        if len(anomalies) > max_options:
            anomalies_display = anomalies.sample(n=max_options, random_state=1).sort_values("date")
            st.caption(f"Showing a random sample of {max_options} for the picker below.")
        else:
            anomalies_display = anomalies.sort_values("date")

        anomalies_display = anomalies_display.reset_index(drop=True)
        anomalies_display["label"] = anomalies_display.apply(
            lambda r: f"{r['date'].date()} — Store {int(r['store_nbr'])} — "
                      f"{FAMILY_NAMES.get(int(r['family']), r['family'])} — actual sales {r['sales']:.1f}",
            axis=1,
        )

        chosen_label = st.selectbox("Pick a flagged anomaly to explain", anomalies_display["label"])
        chosen_row = anomalies_display[anomalies_display["label"] == chosen_label].iloc[0]

        row_X = chosen_row[MODEL_FEATURES].apply(pd.to_numeric, errors="coerce").astype(float)
        row_X_df = pd.DataFrame([row_X.values], columns=MODEL_FEATURES)

        row_shap = explainer.shap_values(row_X_df)[0]
        base_value = explainer.expected_value
        if isinstance(base_value, (list, np.ndarray)):
            base_value = base_value[0]
        predicted = base_value + row_shap.sum()

        m1, m2, m3 = st.columns(3)
        m1.metric("Actual sales", f"{chosen_row['sales']:.1f}")
        m2.metric("Model predicted", f"{predicted:.1f}")
        m3.metric("Baseline (avg. prediction)", f"{base_value:.1f}")

        contrib_df = pd.DataFrame({
            "feature": MODEL_FEATURES,
            "label": [FEATURE_LABELS.get(f, f) for f in MODEL_FEATURES],
            "value": row_X.values,
            "shap": row_shap,
        })
        contrib_df["abs_shap"] = contrib_df["shap"].abs()
        top_contrib = contrib_df.sort_values("abs_shap", ascending=False).head(8)

        fig_wf = go.Figure(go.Bar(
            x=top_contrib.sort_values("shap")["shap"],
            y=top_contrib.sort_values("shap")["label"],
            orientation="h",
            marker_color=["#d62728" if v < 0 else "#2ca02c" for v in top_contrib.sort_values("shap")["shap"]],
        ))
        fig_wf.update_layout(
            height=400, xaxis_title="SHAP contribution (push toward higher / lower sales)",
            yaxis_title="", title="Top drivers for this prediction",
        )
        st.plotly_chart(fig_wf, use_container_width=True)

        st.markdown("**In plain terms:**")
        narrative_top = contrib_df.sort_values("abs_shap", ascending=False).head(4)
        bullets = []
        for _, r in narrative_top.iterrows():
            direction = "pushed the prediction **up**" if r["shap"] > 0 else "pushed the prediction **down**"
            bullets.append(
                f"- **{r['label']}** (value: {r['value']:.2f}) {direction} by about {abs(r['shap']):.1f} units."
            )
        st.markdown("\n".join(bullets))

        residual = chosen_row["sales"] - predicted
        if abs(residual) > 0.1 * max(abs(predicted), 1):
            st.caption(
                f"Note: the model's prediction still misses the actual value by "
                f"~{residual:.1f} units — the flagged features above explain the "
                "model's prediction, not necessarily why the true sales spiked/dropped."
            )

# ===========================================================
# TAB 5 — Model comparison summary
# ===========================================================
with tab_compare:
    st.header("Model Comparison So Far")
    try:
        comp = load_comparison()
        st.dataframe(comp, use_container_width=True)

        if "MAE" in comp.columns and comp["MAE"].max() / max(comp["MAE"].min(), 1e-9) > 100:
            st.caption(
                "⚠️ MAE values span more than two orders of magnitude across rows — "
                "that's usually a sign some rows were fit on a different granularity "
                "(e.g. national aggregate vs. single store-family). Worth double-checking "
                "before treating this table as a like-for-like comparison."
            )
    except FileNotFoundError:
        st.info(f"`{COMPARISON_PATH}` not found in the repo.")
    except Exception as e:
        st.warning(f"Could not load model comparison table: {e}")

    c1, c2 = st.columns(2)
    with c1:
        st.subheader("LightGBM Feature Importance")
        try:
            st.image(FEATURE_IMPORTANCE_IMG, use_container_width=True)
        except Exception:
            st.info("Feature importance image not found.")
    with c2:
        st.subheader("Prophet Components")
        try:
            st.image(PROPHET_IMG, use_container_width=True)
        except Exception:
            st.info("Prophet components image not found.")

# ===========================================================
# TAB 6 — GenAI Analyst (Gemini API, tool-calling + RAG)
# ===========================================================
with tab_genai:
    st.header("🤖 Ask the GenAI Analyst")
    st.caption(
        "Answers are grounded in this app's own pipeline — every number traces back "
        "to a tool call (shown below each response), and real-world context (the 2016 "
        "earthquake, oil price shocks, holiday quirks) is retrieved from a small knowledge base."
    )

    if not GENAI_SDK_AVAILABLE:
        st.error(
            "The `google-genai` package isn't installed. Add `google-genai` to "
            "requirements.txt to enable this tab."
        )
    else:
        genai_api_key = _get_gemini_api_key()
        if not genai_api_key:
            st.warning(
                "No `GEMINI_API_KEY` found in secrets or environment. Get a free key at "
                "[aistudio.google.com/apikey](https://aistudio.google.com/apikey) and add it "
                "as `GEMINI_API_KEY` to `.streamlit/secrets.toml` (locally) or your Streamlit "
                "Cloud app's Secrets settings (deployed)."
            )
        else:
            genai_client = get_genai_client(genai_api_key)

            if "genai_chat_history" not in st.session_state:
                st.session_state.genai_chat_history = []
            if "genai_last_interaction_id" not in st.session_state:
                st.session_state.genai_last_interaction_id = None

            st.markdown("**Try an example:**")
            example_questions = [
                "Why did sales spike around the 2016 earthquake?",
                "Which model has the lowest error overall?",
                "Any flagged anomalies for store 1, family 3 (beverages)?",
            ]
            example_cols = st.columns(len(example_questions))
            clicked_example = None
            for col, q in zip(example_cols, example_questions):
                if col.button(q, use_container_width=True, key=f"genai_ex_{q}"):
                    clicked_example = q

            for msg in st.session_state.genai_chat_history:
                with st.chat_message(msg["role"]):
                    st.markdown(msg["content"])

            typed_q = st.chat_input("Ask about forecasts, drivers, anomalies, or model accuracy…")
            user_q = typed_q or clicked_example

            if user_q:
                st.session_state.genai_chat_history.append({"role": "user", "content": user_q})
                with st.chat_message("user"):
                    st.markdown(user_q)

                with st.chat_message("assistant"):
                    with st.spinner("Thinking…"):
                        try:
                            genai_answer, genai_tool_log, genai_new_id = run_genai_agent(
                                genai_client, user_q, st.session_state.genai_last_interaction_id
                            )
                        except Exception as e:
                            genai_answer = (
                                f"Something went wrong calling the Gemini API: {e}. "
                                "This is often a rate limit on the free tier — wait a "
                                "minute and try again."
                            )
                            genai_tool_log = []
                            genai_new_id = st.session_state.genai_last_interaction_id
                    st.markdown(genai_answer)
                    if genai_tool_log:
                        with st.expander(f"🔧 {len(genai_tool_log)} tool call(s) used"):
                            for t in genai_tool_log:
                                st.json(t)

                st.session_state.genai_last_interaction_id = genai_new_id
                st.session_state.genai_chat_history.append({"role": "assistant", "content": genai_answer})

            st.caption("Powered by the Gemini API (free tier) — replies may take a few seconds.")

st.divider()
st.caption(
    "Built as an interim checkpoint for a 38-day sales forecasting project on the "
    "Corporación Favorita Kaggle dataset. Repo: "
    "[github.com/Elite407/sales-forecasting](https://github.com/Elite407/sales-forecasting)"
)
